"use client";

import { useState, useEffect } from "react";

type Annotation = {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  transliteration: string;
  translation: string;
  notes: string | null;
  pegonText: string | null;
  contributorName: string;
};

export default function PublicCanvas({
  imageUrl,
  annotations,
  fullTransliteration,
  fullTranslation,
  fullApparatus,
}: {
  imageUrl: string;
  annotations: Annotation[];
  fullTransliteration: string;
  fullTranslation: string;
  fullApparatus: string;
}) {
  const [hoveredAnn, setHoveredAnn] = useState<Annotation | null>(null);
  const [selectedAnn, setSelectedAnn] = useState<Annotation | null>(null);
  const [voiceSupported, setVoiceSupported] = useState(false);
  const [speakingId, setSpeakingId] = useState<string | null>(null);

  useEffect(() => {
    if (typeof window !== "undefined" && "speechSynthesis" in window) {
      setVoiceSupported(true);
    }
    return () => {
      if (typeof window !== "undefined" && "speechSynthesis" in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const translitParagraph =
    fullTransliteration.trim() ||
    annotations.map((a) => a.transliteration).join(" ");
  const translationParagraph =
    fullTranslation.trim() ||
    annotations.map((a) => a.translation).join(" ");

  const isAutoGenerated = !fullTransliteration.trim() && annotations.length > 0;

  function findIndonesianVoice(): SpeechSynthesisVoice | null {
    if (!voiceSupported) return null;
    const voices = window.speechSynthesis.getVoices();
    return (
      voices.find((v) => v.lang === "id-ID") ||
      voices.find((v) => v.lang.startsWith("id")) ||
      null
    );
  }

  function speak(text: string, id: string) {
    if (!voiceSupported) return;
    if (speakingId === id) {
      window.speechSynthesis.cancel();
      setSpeakingId(null);
      return;
    }
    window.speechSynthesis.cancel();
    const utt = new SpeechSynthesisUtterance(text);
    utt.lang = "id-ID";
    utt.rate = 0.9;
    const voice = findIndonesianVoice();
    if (voice) utt.voice = voice;
    utt.onend = () => setSpeakingId(null);
    utt.onerror = () => setSpeakingId(null);
    window.speechSynthesis.speak(utt);
    setSpeakingId(id);
  }

  const activeAnn = hoveredAnn || selectedAnn;

  return (
    <div className="space-y-4">
      {/* Info */}
      <div className="flex items-center gap-2 text-sm flex-wrap">
        <span className="text-slate-500 text-xs">
          {annotations.length} kata terverifikasi
        </span>
        {isAutoGenerated && (
          <span className="text-[10px] text-amber-700 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded-full">
            ⚡ Auto dari anotasi
          </span>
        )}
      </div>

      {/* Canvas */}
      <div className="relative bg-sky-50 rounded-xl overflow-hidden border border-sky-100">
        <img
          src={imageUrl}
          alt="Naskah"
          className="w-full block"
          draggable={false}
        />

        {/* Hanya tampilkan kotak yang aktif (hover/selected) */}
        {activeAnn && (
          <div
            className="absolute border-4 border-amber-500 bg-amber-400/30 transition-all duration-150 shadow-lg pointer-events-none z-20"
            style={{
              left: `${activeAnn.x * 100}%`,
              top: `${activeAnn.y * 100}%`,
              width: `${activeAnn.w * 100}%`,
              height: `${activeAnn.h * 100}%`,
            }}
          >
            <div className="absolute -top-9 left-0 bg-amber-500 text-white text-xs font-bold px-2 py-1 rounded shadow-lg whitespace-nowrap">
              {activeAnn.transliteration}
            </div>
          </div>
        )}

        {/* Tooltip ringkas di kanan atas */}
        {hoveredAnn && (
          <div className="absolute z-40 pointer-events-none bg-blue-900/95 text-white rounded-lg shadow-2xl px-3 py-2 w-max max-w-[280px] top-4 right-4">
            <p className="text-[10px] text-sky-300 uppercase tracking-wider mb-1">
              Alih Aksara
            </p>
            <p className="font-semibold text-sm leading-snug">
              {hoveredAnn.transliteration}
            </p>
            <div className="border-t border-blue-800 mt-1.5 pt-1.5">
              <p className="text-[10px] text-sky-300 uppercase tracking-wider mb-0.5">
                Alih Bahasa
              </p>
              <p className="text-xs text-sky-100 leading-snug">
                {hoveredAnn.translation}
              </p>
            </div>
            {hoveredAnn.notes && (
              <div className="border-t border-blue-800 mt-1.5 pt-1.5">
                <p className="text-[10px] text-sky-300 uppercase tracking-wider mb-0.5">
                  Aparatus Kritis
                </p>
                <p className="text-xs text-sky-100 italic leading-snug">
                  {hoveredAnn.notes}
                </p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* 3 KOLOM: ALIH AKSARA | ALIH BAHASA | APARATUS KRITIS */}
      {annotations.length === 0 && !fullTransliteration ? (
        <div className="bg-white border border-sky-100 rounded-xl p-8 text-center text-slate-500 text-sm">
          Belum ada transliterasi untuk halaman ini.
        </div>
      ) : (
        <div className="grid md:grid-cols-3 gap-4">
          {/* Kolom 1: Alih Aksara */}
          <div className="bg-white rounded-xl border border-sky-100 overflow-hidden shadow-sm">
            <div className="bg-blue-900 px-4 py-2.5 flex items-center justify-between">
              <div>
                <p className="text-[11px] font-bold text-white uppercase tracking-wider">
                  Alih Aksara
                </p>
                <p className="text-[9px] text-sky-300 uppercase tracking-wider">
                  Transliterasi Utuh
                </p>
              </div>
              <div className="flex items-center gap-1.5">
                {voiceSupported && (
                  <button
                    onClick={() => speak(translitParagraph, "translit-all")}
                    className={`inline-flex items-center justify-center w-7 h-7 rounded-full transition ${
                      speakingId === "translit-all"
                        ? "bg-amber-500 text-white shadow-md animate-pulse"
                        : "bg-white/20 text-white hover:bg-white/30"
                    }`}
                    title="Putar suara"
                  >
                    {speakingId === "translit-all" ? "⏸" : "🔊"}
                  </button>
                )}
                <span className="px-2 py-0.5 bg-white/20 text-white rounded text-[9px] font-medium uppercase tracking-wide">
                  Latin
                </span>
              </div>
            </div>
            <div className="p-4">
              <HighlightedParagraph
                text={translitParagraph}
                annotations={annotations}
                field="transliteration"
                hoveredId={hoveredAnn?.id || null}
                selectedId={selectedAnn?.id || null}
                onHover={setHoveredAnn}
                onSelect={(a) =>
                  setSelectedAnn(selectedAnn?.id === a.id ? null : a)
                }
              />
            </div>
          </div>

          {/* Kolom 2: Alih Bahasa */}
          <div className="bg-white rounded-xl border border-sky-100 overflow-hidden shadow-sm">
            <div className="bg-teal-700 px-4 py-2.5 flex items-center justify-between">
              <div>
                <p className="text-[11px] font-bold text-white uppercase tracking-wider">
                  Alih Bahasa
                </p>
                <p className="text-[9px] text-teal-200 uppercase tracking-wider">
                  Terjemahan Utuh
                </p>
              </div>
              <div className="flex items-center gap-1.5">
                {voiceSupported && (
                  <button
                    onClick={() =>
                      speak(translationParagraph, "translit-trans")
                    }
                    className={`inline-flex items-center justify-center w-7 h-7 rounded-full transition ${
                      speakingId === "translit-trans"
                        ? "bg-amber-500 text-white shadow-md animate-pulse"
                        : "bg-white/20 text-white hover:bg-white/30"
                    }`}
                    title="Putar suara"
                  >
                    {speakingId === "translit-trans" ? "⏸" : "🔊"}
                  </button>
                )}
                <span className="px-2 py-0.5 bg-white/20 text-white rounded text-[9px] font-medium uppercase tracking-wide">
                  Indonesia
                </span>
              </div>
            </div>
            <div className="p-4">
              <HighlightedParagraph
                text={translationParagraph}
                annotations={annotations}
                field="translation"
                hoveredId={hoveredAnn?.id || null}
                selectedId={selectedAnn?.id || null}
                onHover={setHoveredAnn}
                onSelect={(a) =>
                  setSelectedAnn(selectedAnn?.id === a.id ? null : a)
                }
              />
            </div>
          </div>

          {/* Kolom 3: Aparatus Kritis */}
          <div className="bg-white rounded-xl border border-sky-100 overflow-hidden shadow-sm">
            <div className="bg-slate-700 px-4 py-2.5 flex items-center justify-between">
              <div>
                <p className="text-[11px] font-bold text-white uppercase tracking-wider">
                  Aparatus Kritis
                </p>
                <p className="text-[9px] text-slate-300 uppercase tracking-wider">
                  Catatan Filologis
                </p>
              </div>
              <span className="px-2 py-0.5 bg-white/20 text-white rounded text-[9px] font-medium uppercase tracking-wide">
                Catatan
              </span>
            </div>
            <div className="p-4">
              {fullApparatus && fullApparatus.trim() ? (
                <div className="text-sm text-slate-700 whitespace-pre-wrap leading-relaxed">
                  {fullApparatus}
                </div>
              ) : annotations.some((a) => a.notes) ? (
                <ul className="space-y-2 text-sm text-slate-700">
                  {annotations
                    .filter((a) => a.notes)
                    .map((a, i) => (
                      <li
                        key={a.id}
                        className="flex gap-2 cursor-pointer hover:bg-sky-50 rounded px-1 -mx-1 py-0.5 transition"
                        onMouseEnter={() => setHoveredAnn(a)}
                        onMouseLeave={() => setHoveredAnn(null)}
                        onClick={() =>
                          setSelectedAnn(selectedAnn?.id === a.id ? null : a)
                        }
                      >
                        <span className="text-[10px] font-bold text-slate-500 shrink-0 mt-0.5">
                          {i + 1}.
                        </span>
                        <div>
                          <span className="font-medium text-blue-900">
                            {a.transliteration}
                          </span>
                          <span className="text-slate-500"> — </span>
                          <span className="italic">{a.notes}</span>
                        </div>
                      </li>
                    ))}
                </ul>
              ) : (
                <p className="text-sm text-slate-400 italic">
                  Belum ada aparatus kritis untuk halaman ini.
                </p>
              )}
            </div>
          </div>
        </div>
      )}

      <p className="text-xs text-slate-500">
        💡 Arahkan kursor ke kata berwarna di paragraf untuk melihat posisinya
        di gambar naskah. Klik untuk detail lengkap.
      </p>

      {/* Detail panel */}
      {selectedAnn && (
        <div className="bg-white border border-sky-100 rounded-xl p-5 shadow-md">
          <div className="flex items-start justify-between mb-3">
            <div className="flex items-center gap-2">
              <div className="w-1 h-5 bg-teal-500 rounded"></div>
              <h3 className="font-bold text-blue-900">Detail Anotasi</h3>
            </div>
            <div className="flex items-center gap-3">
              <span className="text-xs text-slate-500">
                oleh {selectedAnn.contributorName}
              </span>
              <button
                onClick={() => setSelectedAnn(null)}
                className="text-xs text-slate-500 hover:text-teal-700 hover:underline"
              >
                Tutup
              </button>
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-xs text-slate-500 mb-0.5">Transliterasi</p>
              <p className="font-medium text-blue-900">
                {selectedAnn.transliteration}
              </p>
              {selectedAnn.pegonText && (
                <p className="text-xs text-slate-500 mt-1 font-mono">
                  {selectedAnn.pegonText}
                </p>
              )}
            </div>
            <div>
              <p className="text-xs text-slate-500 mb-0.5">Terjemahan</p>
              <p className="text-slate-700">{selectedAnn.translation}</p>
            </div>
          </div>

          {selectedAnn.notes && (
            <div className="mt-3 pt-3 border-t border-sky-100 text-sm">
              <p className="text-xs text-slate-500 mb-0.5">
                Aparatus Kritis
              </p>
              <p className="text-slate-600 italic">{selectedAnn.notes}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// Komponen paragraf dengan highlight per kata
function HighlightedParagraph({
  text,
  annotations,
  field,
  hoveredId,
  selectedId,
  onHover,
  onSelect,
}: {
  text: string;
  annotations: Annotation[];
  field: "transliteration" | "translation";
  hoveredId: string | null;
  selectedId: string | null;
  onHover: (a: Annotation | null) => void;
  onSelect: (a: Annotation) => void;
}) {
  if (!text.trim()) {
    return <p className="text-sm text-slate-400 italic">—</p>;
  }

  const wordMap = new Map<string, Annotation>();
  annotations.forEach((a) => {
    const value = a[field];
    const words = value.split(/\s+/).filter((w) => w.length > 0);
    words.forEach((w) => {
      const key = w.toLowerCase().replace(/[^\w\u00C0-\u024F]/g, "");
      if (key && !wordMap.has(key)) {
        wordMap.set(key, a);
      }
    });
  });

  const tokens = text.split(/(\s+)/);

  return (
    <p className="text-sm leading-relaxed text-slate-800">
      {tokens.map((token, i) => {
        if (!token.trim()) {
          return <span key={i}>{token}</span>;
        }

        const clean = token.toLowerCase().replace(/[^\w\u00C0-\u024F]/g, "");
        const ann = clean ? wordMap.get(clean) : null;

        if (ann) {
          const isActive = ann.id === hoveredId || ann.id === selectedId;
          const baseColor =
            field === "transliteration"
              ? "bg-amber-100 text-blue-900 border-b-2 border-amber-400"
              : "bg-teal-100 text-teal-900 border-b-2 border-teal-400";
          const activeColor =
            field === "transliteration"
              ? "bg-amber-300 text-blue-900 border-b-2 border-amber-500 shadow-sm"
              : "bg-teal-300 text-teal-900 border-b-2 border-teal-500 shadow-sm";

          return (
            <mark
              key={i}
              className={`${
                isActive ? activeColor : baseColor
              } px-0.5 rounded cursor-pointer transition-all`}
              onMouseEnter={() => onHover(ann)}
              onMouseLeave={() => onHover(null)}
              onClick={() => onSelect(ann)}
            >
              {token}
            </mark>
          );
        }

        return <span key={i}>{token}</span>;
      })}
    </p>
  );
}